### ISSUE TITLE
Spacing issues

### ISSUE THREAD

**Issue by wesoda25** [nfreader/slimbus#23]
![chrome_Elxt5xZjAn](https://user-images.githubusercontent.com/37246588/94498073-3426a680-01c7-11eb-8aa0-7d49ccaff0f1.png)
----asdoasd--------------
![chrome_T5CU85xlee](https://user-images.githubusercontent.com/37246588/94498085-38eb5a80-01c7-11eb-977b-e1ae1e30f350.png)
(from notes/bans)

**Comment by nfreader** [comment]
Yeah I've seen that, I have no clue why that's happening. Call it under investigation.

**Comment by nfreader** [comment]
This is an issue with the templating engine (twig) and PHP 7.4.
https://stackoverflow.com/questions/59248533/twig-problem-with-php-7-4-in-write-variable
I'll see what I can do to resolve it without waiting for an update.

**Comment by nfreader** [comment]
Oh, just needed a version bump on the server. All fixed!
