### ISSUE TITLE
statbus/me page does not tell the chart scale

### ISSUE THREAD

**Issue by Pyko1** [nfreader/slimbus#5]
The page does not have any input on the timescale of the jobs played.
It should tell what the chart represents on jobs played.

Also even preferrably would be to see time/times played both on a toggle.

**Comment by nfreader** [comment]
We only track the number of minutes as a given role. The number of _times_ you’ve played could be parsed out of `manifest.txt`, but that’s not really feasible. 

A scale might be possible. It depends on how intensive that query is.

**Comment by Pyko1** [comment]
On the player stat pages it says its minutes played.
But on the /me page it does not tell the time frame, thus have seen people think it was hours or rounds.
